server:
  port: 5600

spring:
  application:
    name: muzyka

  jpa:
    hibernate:
      ddl-auto: update
  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: Admin
    password: PanConPalta1@

  # autoconfigure:
  #   exclude:
  #     - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  #     - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
