server:
  port: 5600

spring:
  application:
    name: muzyka
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false # To address the WARN message about open-in-view

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE # To see parameter binding
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:muzyka
    username: sa
    password: 

jwt:
  secret: c3VwZXJzZWNyZXRrZXlmb3Jqd3R0b2tlbmlzYmVycmx5bG9uZ2FuZHN0cm9uZw== # Placeholder, replace with a strong, base64-encoded secret
  expiration: 86400000 # 24 hours in milliseconds

  # autoconfigure:
  #   exclude:
  #     - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  #     - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
