server:
  port: 5600

spring:
  application:
    name: muzyka
  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@muzykabd_high?TNS_ADMIN=./wallet
    username: admin
    password: Muzykacontraseña369
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        # ESTA ES LA CLAVE: Cambia 'PhysicalNamingStrategyStandardImpl' por esta línea:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      # Desactivamos las comillas globales para evitar conflictos con Oracle
      hibernate.globally_quoted_identifiers: false
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: c3VwZXJzZWNyZXRrZXlmb3Jqd3R0b2tlbmlzYmVycmx5bG9uZ2FuZHN0cm9uZw==
  expiration: 86400000
